language: python
python: 3.9
cache:
  pip: true
  directories:
    - $HOME/.cache/pkgcheck

install:
  # use pkgcheck from git for --exit support, revert to pypi on new release
  - pip install https://github.com/pkgcore/pkgcheck/archive/master.tar.gz
before_script:
  # force PATH to include pip installed executables
  - sudo env "PATH=$PATH" pmaint sync gentoo
script:
  # run as root to support squashfs repo mounting
  - sudo env "PATH=$PATH" pkgcheck scan -v --exit
